version: '3.3'

services:

  tictactoefront:
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true 
    volumes:
      - '.:/tictactoe-client'
      - '/tictactoe-client/node_modules'
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
